<wsdl:definitions
     name="PollSalaryChangesTable"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOA/SalaryChangeProcessing/PollSalaryChangesTable"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOA/SalaryChangeProcessing/PollSalaryChangesTable"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollSalaryChangesTable"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="PollSalaryChangesTable_plt" >
    <plt:role name="PollSalaryChangesTable_role" >
      <plt:portType name="tns:PollSalaryChangesTable_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollSalaryChangesTable" schemaLocation="../Schemas/PollSalaryChangesTable_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="SalaryChangesCollection_msg">
        <wsdl:part name="SalaryChangesCollection" element="top:SalaryChangesCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollSalaryChangesTable_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:SalaryChangesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
